package com.java.samples.hibernate.employeeapp.entity;
// Generated Aug 3, 2020 11:03:53 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "employee_db")
public class Employee implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private int id;

	@Column(name = "first_Name", length = 30)
	private String firstName;

	@Column(name = "last_Name", length = 30)
	private String lastName;

	@Column(name = "salary")
	private Integer salary;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee", cascade = CascadeType.ALL) // without CascadeType.ALL child rows are not inserting
	private Set<Phone> phones;

	public Employee() {

	}

	public Employee(int id) {

		this.id = id;
	}

	public Employee(String firstName, String lastName, int salary) {

		this.firstName = firstName;
		this.lastName = lastName;
		this.salary = salary;
	}

	public Employee(int id, String firstName, String lastName, Integer salary, Set<Phone> phones) {

		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.salary = salary;
		this.phones = phones;
	}

	public int getId() {

		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFirstName() {

		return this.firstName;
	}

	public void setFirstName(String firstName) {

		this.firstName = firstName;
	}

	public String getLastName() {

		return this.lastName;
	}

	public void setLastName(String lastName) {

		this.lastName = lastName;
	}

	public Integer getSalary() {

		return this.salary;
	}

	public void setSalary(Integer salary) {

		this.salary = salary;
	}

	public Set<Phone> getPhones() {

		return this.phones;
	}

	public void setPhones(Set<Phone> phones) {

		this.phones = phones;
	}

	public void addPhone(Phone phone) { // without this helper method child rows are inserting without parent id
		
		if (phones == null) {
			
			phones = new HashSet<>();
		}
		
		phone.setEmployee(this);
		phones.add(phone);
	}
}
